version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.3
  gh: circleci/github-cli@1.0
  maven: circleci/maven@1.1
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  create-pr-from-develop-to-main:
    docker:
      - image: 'cimg/base:stable'
    parameters:
      token:
        description: |
          Pass Github token
        type: env_var_name
    steps:
      - gh/setup
      - gh/clone
      - run:
          command: |
            PR_STATUS=$(gh pr view --json state | jq -r .state)
            if [[ "$PR_STATUS" = "OPEN" ]]; then echo "PR already open" ; else gh pr create --title "PR develop -> main" --body "PR from develop branch to main branch" --reviewer HendrikTredoux --base main; fi
          name: Create Pull Request

  build-and-deploy-artifact:
    parameters:
      branch:
        description: |
          Specify branch
        type: string

    docker:
      - image: 'cimg/openjdk:11.0'

    steps:
      - attach_workspace:
          at: .

      - checkout
      - aws-cli/install

      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          name: Generate Cache Checksum
          working_directory: $CIRCLE_WORKING_DIRECTORY

      - restore_cache:
          key: 'maven-{{ checksum "/tmp/maven_cache_seed" }}'

      - run:
          command: |
            mkdir -p ~/.m2
            echo $SETTINGS_SECURITY_XML | base64 -d > ~/.m2/settings-security.xml
            echo $SETTINGS_XML | base64 -d > ~/.m2/settings.xml
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            echo 'export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain westerra --domain-owner 181741612687 --query authorizationToken --output text)' >> $BASH_ENV

      - run:
          name: Deploy trexis-backbase-identity-ingestion-authenticator
          command: |
            mvn -s ~/.m2/settings.xml -f pom.xml clean install deploy

      - save_cache:
          key: 'maven-{{ checksum "/tmp/maven_cache_seed" }}'
          paths:
            - ~/.m2

      - persist_to_workspace:
          root: .
          paths:
            - .


workflows:
  deployment:
    jobs:
      - build-and-deploy-artifact:
          name: build-and-deploy-artifact-for-trexis-backbase-identity-ingestion-authenticator-for-develop-branch
          branch: develop
          context: bb-aws-dev
          filters:
            branches:
              only:
                - develop

      - build-and-deploy-artifact:
          name: build-and-deploy-artifact-for-trexis-backbase-identity-ingestion-authenticator-for-main-branch
          branch: main
          context: bb-aws-dev
          filters:
            branches:
              only:
                - main

      - approval-for-creating-pr-from-develop-to-main:
          requires:
            - build-and-deploy-artifact-for-trexis-backbase-identity-ingestion-authenticator-for-develop-branch
          type: approval      
          filters:
            branches:
              only:
                - develop

      - create-pr-from-develop-to-main:
          requires:
            - approval-for-creating-pr-from-develop-to-main
          token: GITHUB_TOKEN       
          filters:
            branches:
              only:
                - develop