apiVersion: v1
description: A Helm chart for Template repo
name: trexis-backbase-identity-ingestion-authenticator
version: 1.0.0
home: https://github.com/westerra/trexis-backbase-identity-ingestion-authenticator
maintainers:
- name: Vishnu Nair
  email: vishnu.nair@trexis.net
